FROM alpine:3

LABEL authors="Ahmad Usamah Ali"
LABEL company="Tugas Sister Kelas A" website="https://www.itk.ac.id"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"